# Generated by Django 4.2 on 2024-11-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='work_experiences',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
